### Create a folder in Document Manager
POST http://localhost:4004/odata/v4/document/createFolder
Content-Type: application/json

{
  "repositoryId": "9d0f2204-45e9-4a99-b2a1-134e1b8a0106",
  "folderName": "MyNewFolder"
}

### List folders in a repository
POST http://localhost:4004/odata/v4/document/listFolders
Content-Type: application/json

{
  "repositoryId": "9d0f2204-45e9-4a99-b2a1-134e1b8a0106"
}

### Delete a folder in Document Manager
POST http://localhost:4004/odata/v4/document/deleteFolder
Content-Type: application/json

{
  "cmisId": "<paste-cmisId-here>"
}

### List all repositories
POST http://localhost:4004/odata/v4/document/listRepositories
Content-Type: application/json

{}

### Onboard a repository in Document Manager
POST http://localhost:4004/odata/v4/document/onboardRepository
Content-Type: application/json

{
  "repoName": "ABAPCodeReviewRepository",
  "repoDescription": "Internal document repository"
}

### Delete a repository in Document Manager
POST http://localhost:4004/odata/v4/document/deleteRepository
Content-Type: application/json

{
  "repositoryId": "1c73ab7e-2187-4cf9-ad37-ca9a2222fdfb"
}

### Create a document in SAP Cloud ALM (via CALM_API destination)
POST http://localhost:4004/odata/v4/document/createCloudALMDocument
Content-Type: application/json

{
  "projectUUID": "11111111-1111-1111-1111-111111111111",
  "title": "My CAP Uploaded Document",
  "documentTypeCode": "FU",
  "statusCode": "30"
}

### Create a document in SAP Cloud ALM (via CALM_API destination)
GET http://localhost:4004/odata/v4/document/$metadata

### Get Cloud ALM Document Service $metadata
POST http://localhost:4004/odata/v4/document/getCloudALMMetadata
Content-Type: application/json

{}

### Get Cloud ALM Sandbox Metadata (via SAP Business Accelerator Hub)
POST http://localhost:4004/odata/v4/document/getCloudALMSandboxMetadata
Content-Type: application/json

{}



